// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: sensitive_word_rpc/sensitive_word_rpc.proto

package sensitive_word_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperateSensitiveWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *OperateSensitiveWordRequest) Reset() {
	*x = OperateSensitiveWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateSensitiveWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateSensitiveWordRequest) ProtoMessage() {}

func (x *OperateSensitiveWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateSensitiveWordRequest.ProtoReflect.Descriptor instead.
func (*OperateSensitiveWordRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *OperateSensitiveWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type OperateSensitiveWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *OperateSensitiveWordResponse) Reset() {
	*x = OperateSensitiveWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateSensitiveWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateSensitiveWordResponse) ProtoMessage() {}

func (x *OperateSensitiveWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateSensitiveWordResponse.ProtoReflect.Descriptor instead.
func (*OperateSensitiveWordResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *OperateSensitiveWordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckSensitiveWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *CheckSensitiveWordRequest) Reset() {
	*x = CheckSensitiveWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSensitiveWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSensitiveWordRequest) ProtoMessage() {}

func (x *CheckSensitiveWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSensitiveWordRequest.ProtoReflect.Descriptor instead.
func (*CheckSensitiveWordRequest) Descriptor() ([]byte, []int) {
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSensitiveWordRequest) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type CheckSensitiveWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*CheckSensitiveWordResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CheckSensitiveWordResponse) Reset() {
	*x = CheckSensitiveWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSensitiveWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSensitiveWordResponse) ProtoMessage() {}

func (x *CheckSensitiveWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSensitiveWordResponse.ProtoReflect.Descriptor instead.
func (*CheckSensitiveWordResponse) Descriptor() ([]byte, []int) {
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *CheckSensitiveWordResponse) GetResults() []*CheckSensitiveWordResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type CheckSensitiveWordResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Words     []string `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	HitWords  []string `protobuf:"bytes,3,rep,name=hit_words,json=hitWords,proto3" json:"hit_words,omitempty"`
	Sensitive bool     `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
}

func (x *CheckSensitiveWordResponse_Result) Reset() {
	*x = CheckSensitiveWordResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSensitiveWordResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSensitiveWordResponse_Result) ProtoMessage() {}

func (x *CheckSensitiveWordResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSensitiveWordResponse_Result.ProtoReflect.Descriptor instead.
func (*CheckSensitiveWordResponse_Result) Descriptor() ([]byte, []int) {
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CheckSensitiveWordResponse_Result) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CheckSensitiveWordResponse_Result) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *CheckSensitiveWordResponse_Result) GetHitWords() []string {
	if x != nil {
		return x.HitWords
	}
	return nil
}

func (x *CheckSensitiveWordResponse_Result) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

var File_sensitive_word_rpc_sensitive_word_rpc_proto protoreflect.FileDescriptor

var file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64,
	0x5f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70,
	0x63, 0x22, 0x31, 0x0a, 0x1b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x38, 0x0a, 0x1c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31,
	0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0xdc, 0x01, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4f, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x6d, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x69, 0x74, 0x5f, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x68, 0x69, 0x74, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x32, 0xfb, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x77, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x2f, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7a, 0x0a, 0x13, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x2f, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f,
	0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x2d, 0x2e,
	0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x73,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e,
	0x5a, 0x2c, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescOnce sync.Once
	file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescData = file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDesc
)

func file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescGZIP() []byte {
	file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescOnce.Do(func() {
		file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescData)
	})
	return file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDescData
}

var file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sensitive_word_rpc_sensitive_word_rpc_proto_goTypes = []interface{}{
	(*OperateSensitiveWordRequest)(nil),       // 0: sensitive_word_rpc.OperateSensitiveWordRequest
	(*OperateSensitiveWordResponse)(nil),      // 1: sensitive_word_rpc.OperateSensitiveWordResponse
	(*CheckSensitiveWordRequest)(nil),         // 2: sensitive_word_rpc.CheckSensitiveWordRequest
	(*CheckSensitiveWordResponse)(nil),        // 3: sensitive_word_rpc.CheckSensitiveWordResponse
	(*CheckSensitiveWordResponse_Result)(nil), // 4: sensitive_word_rpc.CheckSensitiveWordResponse.Result
}
var file_sensitive_word_rpc_sensitive_word_rpc_proto_depIdxs = []int32{
	4, // 0: sensitive_word_rpc.CheckSensitiveWordResponse.results:type_name -> sensitive_word_rpc.CheckSensitiveWordResponse.Result
	0, // 1: sensitive_word_rpc.SensitiveWord.AddSensitiveWord:input_type -> sensitive_word_rpc.OperateSensitiveWordRequest
	0, // 2: sensitive_word_rpc.SensitiveWord.RemoveSensitiveWord:input_type -> sensitive_word_rpc.OperateSensitiveWordRequest
	2, // 3: sensitive_word_rpc.SensitiveWord.CheckSensitiveWord:input_type -> sensitive_word_rpc.CheckSensitiveWordRequest
	1, // 4: sensitive_word_rpc.SensitiveWord.AddSensitiveWord:output_type -> sensitive_word_rpc.OperateSensitiveWordResponse
	1, // 5: sensitive_word_rpc.SensitiveWord.RemoveSensitiveWord:output_type -> sensitive_word_rpc.OperateSensitiveWordResponse
	3, // 6: sensitive_word_rpc.SensitiveWord.CheckSensitiveWord:output_type -> sensitive_word_rpc.CheckSensitiveWordResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sensitive_word_rpc_sensitive_word_rpc_proto_init() }
func file_sensitive_word_rpc_sensitive_word_rpc_proto_init() {
	if File_sensitive_word_rpc_sensitive_word_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateSensitiveWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateSensitiveWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSensitiveWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSensitiveWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSensitiveWordResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensitive_word_rpc_sensitive_word_rpc_proto_goTypes,
		DependencyIndexes: file_sensitive_word_rpc_sensitive_word_rpc_proto_depIdxs,
		MessageInfos:      file_sensitive_word_rpc_sensitive_word_rpc_proto_msgTypes,
	}.Build()
	File_sensitive_word_rpc_sensitive_word_rpc_proto = out.File
	file_sensitive_word_rpc_sensitive_word_rpc_proto_rawDesc = nil
	file_sensitive_word_rpc_sensitive_word_rpc_proto_goTypes = nil
	file_sensitive_word_rpc_sensitive_word_rpc_proto_depIdxs = nil
}
