// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "cixn",
            "url": "https://blog.zhangziwen.cn",
            "email": "zeco11320@163.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "test service useful",
                "tags": [
                    "Common"
                ],
                "summary": "PING TEST",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sensitive_word_service": {
            "get": {
                "description": "检查词是否敏感",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Word"
                ],
                "summary": "检查词是否敏感",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ldap userid 仅在开发环境需要提供",
                        "name": "x-ldap-user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "name": "words",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http_util.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "info": {
                                            "$ref": "#/definitions/sensitive_word_service.CheckSensitiveWordResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "添加词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Word"
                ],
                "summary": "添加词",
                "parameters": [
                    {
                        "description": "add word",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sensitive_word_controller.operateWordParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_util.HttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "移除词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Word"
                ],
                "summary": "移除词",
                "parameters": [
                    {
                        "description": "delete word",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sensitive_word_controller.operateWordParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_util.HttpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_util.HttpResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "info": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "sensitive_word_controller.operateWordParam": {
            "type": "object",
            "required": [
                "word"
            ],
            "properties": {
                "word": {
                    "type": "string"
                }
            }
        },
        "sensitive_word_service.CheckSensitiveWordResult": {
            "type": "object",
            "properties": {
                "hit_words": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sensitive": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Words Check API DOC",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
